# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class kb_trimmomatic(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def runTrimmomatic(self, input_params, context=None):
        """
        :param input_params: instance of type "runTrimmomaticInput"
           (runTrimmomatic() ** ** to backend a KBase App, potentially
           operating on ReadSets) -> structure: parameter "input_ws" of type
           "workspace_name" (** Common types), parameter "input_reads_ref" of
           type "data_obj_ref", parameter "output_ws" of type
           "workspace_name" (** Common types), parameter "output_reads_name"
           of type "data_obj_name", parameter "read_type" of String,
           parameter "quality_encoding" of String, parameter "adapter_clip"
           of type "AdapterClip_Options" -> structure: parameter "adapterFa"
           of String, parameter "seed_mismatches" of Long, parameter
           "palindrome_clip_threshold" of Long, parameter
           "simple_clip_threshold" of Long, parameter "sliding_window" of
           type "SlidingWindow_Options" (parameter groups) -> structure:
           parameter "sliding_window_size" of Long, parameter
           "sliding_window_min_quality" of Long, parameter
           "leading_min_quality" of Long, parameter "trailing_min_quality" of
           Long, parameter "crop_length" of Long, parameter
           "head_crop_length" of Long, parameter "min_length" of Long
        :returns: instance of type "runTrimmomaticOutput" -> structure:
           parameter "report_name" of String, parameter "report_ref" of String
        """
        return self._client.call_method(
            'kb_trimmomatic.runTrimmomatic',
            [input_params], self._service_ver, context)

    def execTrimmomatic(self, input_params, context=None):
        """
        :param input_params: instance of type "execTrimmomaticInput"
           (execTrimmomatic() ** ** the local method that runs Trimmomatic on
           each read library) -> structure: parameter "input_reads_ref" of
           type "data_obj_ref", parameter "output_ws" of type
           "workspace_name" (** Common types), parameter "output_reads_name"
           of type "data_obj_name", parameter "read_type" of String,
           parameter "adapterFa" of String, parameter "seed_mismatches" of
           Long, parameter "palindrome_clip_threshold" of Long, parameter
           "simple_clip_threshold" of Long, parameter "quality_encoding" of
           String, parameter "sliding_window_size" of Long, parameter
           "sliding_window_min_quality" of Long, parameter
           "leading_min_quality" of Long, parameter "trailing_min_quality" of
           Long, parameter "crop_length" of Long, parameter
           "head_crop_length" of Long, parameter "min_length" of Long
        :returns: instance of type "execTrimmomaticOutput" -> structure:
           parameter "output_filtered_ref" of type "data_obj_ref", parameter
           "output_unpaired_fwd_ref" of type "data_obj_ref", parameter
           "output_unpaired_rev_ref" of type "data_obj_ref", parameter
           "report" of String
        """
        return self._client.call_method(
            'kb_trimmomatic.execTrimmomatic',
            [input_params], self._service_ver, context)

    def execTrimmomaticSingleLibrary(self, input_params, context=None):
        """
        :param input_params: instance of type "execTrimmomaticInput"
           (execTrimmomatic() ** ** the local method that runs Trimmomatic on
           each read library) -> structure: parameter "input_reads_ref" of
           type "data_obj_ref", parameter "output_ws" of type
           "workspace_name" (** Common types), parameter "output_reads_name"
           of type "data_obj_name", parameter "read_type" of String,
           parameter "adapterFa" of String, parameter "seed_mismatches" of
           Long, parameter "palindrome_clip_threshold" of Long, parameter
           "simple_clip_threshold" of Long, parameter "quality_encoding" of
           String, parameter "sliding_window_size" of Long, parameter
           "sliding_window_min_quality" of Long, parameter
           "leading_min_quality" of Long, parameter "trailing_min_quality" of
           Long, parameter "crop_length" of Long, parameter
           "head_crop_length" of Long, parameter "min_length" of Long
        :returns: instance of type "execTrimmomaticOutput" -> structure:
           parameter "output_filtered_ref" of type "data_obj_ref", parameter
           "output_unpaired_fwd_ref" of type "data_obj_ref", parameter
           "output_unpaired_rev_ref" of type "data_obj_ref", parameter
           "report" of String
        """
        return self._client.call_method(
            'kb_trimmomatic.execTrimmomaticSingleLibrary',
            [input_params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('kb_trimmomatic.status',
            [], self._service_ver, context)
